const WORDS: &[&str] = &[
    "APPLE", "ART", "ARTY", "BARN", "BEAR", "BIRD", "BLADE", "BRAIN", "BRAVE", "CABIN", "CABLE", "CANDY", "CARE", "CARD", "CAVE", "CHAIR", "CHAT", "CHIP", "CLAP", "CLARITY", "CLEAN", "CLIMB", "CLOCK", "CLOUD", "COAST", "COLD", "COMB", "CORE", "CRAFT", "CROWN", "DARE", "DARK", "DATE", "DAWN", "DEAL", "DEEP", "DEER", "DESK", "DICE", "DIVE", "DRAGON", "DREAM", "EARN", "EAST", "EASY", "EDGE", "EGG", "EIGHT", "ELBOW", "ELSE", "FAME", "FARM", "FAST", "FEAR", "FEEL", "FERN", "FIND", "FIRE", "FISH", "FLAME", "FLAT", "FLY", "FOLD", "FOOD", "FOOT", "FOREST", "FORM", "FRESH", "FROG", "GAME", "GATE", "GEAR", "GHOST", "GIFT", "GLOW", "GOAT", "GOLD", "GRAPE", "GRASS", "GREAT", "GREEN", "GRID", "GROW", "HAND", "HAT", "HAZE", "HEAD", "HEAR", "HEART", "HEAT", "HILL", "HIVE", "HOME", "HONEY", "HOPE", "HORN", "HORSE", "ICE", "IDEA", "IRON", "ISLAND", "JAZZ", "JUMP", "KEEP", "KITE", "KNIGHT", "LAMP", "LAND", "LARGE", "LATE", "LEAF", "LIGHT", "LION", "LIST", "LIVE", "LOAF", "LONG", "LOOP", "LUCK", "MAGIC", "MAP", "MARCH", "MARK", "MINT", "MOON", "MOUSE", "MOVE", "MUSIC", "NEST", "NICE", "NIGHT", "NOSE", "NOTE", "OAK", "OCEAN", "ORBIT", "PAGE", "PAINT", "PARK", "PATH", "PEAR", "PEARL", "PENGUIN", "PINK", "PLANT", "PLAY", "PLUM", "POEM", "POINT", "POLAR", "QUICK", "QUIET", "RAIN", "RAINBOW", "READ", "REAL", "RED", "RING", "RIVER", "ROAD", "ROCK", "ROSE", "RUST", "SAFE", "SAND", "SCORE", "SEA", "SHARK", "SHIP", "SHOE", "SHORT", "SILK", "SING", "SKATE", "SKY", "SLATE", "SLEEP", "SLIDE", "SLOTH", "SNAP", "SNOW", "SOFT", "SONG", "SPACE", "SPARK", "SPELL", "SPIN", "STAR", "STARE", "STONE", "STORM", "STORY", "SUN", "SWAN", "TABLE", "TAME", "TASTE", "TEAM", "TEA", "TIGER", "TIME", "TINY", "TOAST", "TOE", "TREE", "TRICK", "TRUE", "TRY", "TUNE", "TURTLE", "TWIN", "TYPE", "VAST", "VIBE", "VIEW", "VINE", "VOTE", "WARM", "WAVE", "WAY", "WEB", "WELL", "WHALE", "WILD", "WIND", "WING", "WISE", "WORD", "WORK", "WORLD", "YARN", "YELLOW", "YET", "ZEBRA", "ATE", "EAT"
];

const COMMON_WORDS: &[&str] = &[
    "AND", "ANY", "ARE", "ARM", "ATE", "BAD", "BAG", "BAT", "BED", "BIG", "BIT", "BOX", "BUY", "CAN", "CAP", "CAR", "CAT", "COW", "CRY", "CUP", "CUT", "DAY", "DID", "DIE", "DOG", "DOT", "DRY", "EAR", "EAT", "END", "ERA", "EYE", "FAN", "FAR", "FAT", "FEW", "FIT", "FIX", "FOG", "FUN", "GAP", "GAS", "GET", "GOD", "GUM", "GUY", "HAS", "HAY", "HEN", "HER", "HIM", "HIS", "HIT", "HOW", "HUG", "HUT", "ILL", "INK", "JAM", "JET", "JOB", "JOY", "KEY", "KID", "KIT", "LAB", "LAP", "LAW", "LAY", "LEG", "LET", "LIE", "LOG", "LOT", "LOW", "MAN", "MAT", "MAY", "MEN", "MIX", "MOM", "NET", "NEW", "NOD", "NOT", "NOW", "NUT", "OAR", "OAT", "OFF", "OIL", "OLD", "ONE", "OWL", "OWN", "PAN", "PAT", "PAY", "PEN", "PET", "PIG", "PIN", "POT", "PUT", "RAG", "RAM", "RAN", "RAP", "RAT", "RAW", "RAY", "RED", "RID", "RIG", "RIP", "ROB", "ROD", "RUG", "RUN", "SAD", "SAP", "SAT", "SAW", "SAY", "SEA", "SEE", "SET", "SEW", "SHE", "SHY", "SIR", "SIT", "SIX", "SOW", "SPA", "SPY", "SUB", "SUE", "SUM", "TAB", "TAG", "TAN", "TAP", "TAR", "TAX", "TEA", "TIE", "TIN", "TIP", "TOE", "TOP", "TOW", "TOY", "TRY", "TUB", "TWO", "USE", "VAN", "VAT", "VIA", "VOW", "WAR", "WAS", "WAX", "WAY", "WHO", "WHY", "WIN", "WIT", "WON", "WOW", "YES", "YET", "YOU", "ZOO"
];

pub fn is_word(word: &str) -> bool {
    WORDS.contains(&word) || COMMON_WORDS.contains(&word)
}
